( couleurs maison etre (list rose vert rouge bleu) )
( couleurs maison etre (list jaune jaune jaune jaune jaune) )
( Anglais vivre maison rose )
( Anglais avoir domestiques animaux licornes )
( personne boire the avoir oiseaux )
( maison rose etre gauche maison verte )
( propri�taire maison bleue fumer Pall_Mall )
( personne fumer Pall_Mall avoir chiens )
( propri�taire maison rouge fumer Dunhill )
( personne vivre maison centre boire chiens )
( personne vivre maison centre boire eau )
( Anglais habiter il vivre c�t� maison verte maison premi�re )
( homme fumer Blend vivre c�t� celui avoir chats )
( propri�taire fumer Blue_Master boire bi�re )
( Allemand fumer Prince )
( homme avoir oiseaux avoir voisin boire eau )
