(assert (etre(Trotro,aimer(garçon,surprises))))
(assert (vivre(il,montréal)))
(assert (avoir(Trotro,yeux(bleus))))
(assert (etre(Trotro,moche(malheureux))))
(assert (etre(Trotro,Papa)))
(assert (rigoler(Papa,maison(Trotro))))
(assert (jouer(on,fauteuil(Papa))))
(assert (rendre(Trotro,services(Maman))))
